apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.36.0 (ae2a39403)
  labels:
    io.kompose.service: eureka-server
  name: eureka-server
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: eureka-server
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.36.0 (ae2a39403)
      labels:
        io.kompose.service: eureka-server
    spec:
      containers:
        - env:
            - name: EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE
              value: http://eureka-server:8761/eureka
            - name: SPRING_CLOUD_CONFIG_URI
              value: http://config-server:8081
          image: matiasvejar/eureka-server:latest
          imagePullPolicy: IfNotPresent
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8761
            failureThreshold: 10
            initialDelaySeconds: 60
            periodSeconds: 15
            timeoutSeconds: 10
          name: eureka-server
          ports:
            - containerPort: 8761
              protocol: TCP
      restartPolicy: Always