apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-nginx-cm
data:
  default.conf: |
    server {
      listen       80;
      root   /usr/share/nginx/html;
      index  index.html;
      # SPA fallback
      location / {
        try_files $uri $uri/ /index.html;
      }
      
      location /api/ {
        proxy_pass       http://gateway-server:8080/api/;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
      }
    }