apiVersion: v1
kind: Service
metadata:
  name: gateway-server
  labels:
    io.kompose.service: gateway-server
spec:
  type: NodePort
  selector:
    io.kompose.service: gateway-server
  ports:
    - port: 8080         
      targetPort: 8080   
      nodePort: 30804    