#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL
  CREATE DATABASE ms1;
  CREATE DATABASE ms2;
  CREATE DATABASE ms3;
  CREATE DATABASE ms4;
  CREATE DATABASE ms5;
  CREATE DATABASE ms6;
  CREATE DATABASE ms7;
EOSQL
