apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Program Files\Kompose\kompose.exe convert
    kompose.version: 1.36.0 (ae2a39403)
  labels:
    io.kompose.service: ms1
  name: ms1
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: ms1
  template:
    metadata:
      annotations:
        kompose.cmd: C:\Program Files\Kompose\kompose.exe convert
        kompose.version: 1.36.0 (ae2a39403)
      labels:
        io.kompose.service: ms1
    spec:
      containers:
        - env:
            - name: EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE
              value: http://eureka-server:8761/eureka
            - name: PORT
              value: "0"
            - name: SPRING_CLOUD_CONFIG_URI
              value: http://config-server:8081
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          image: matiasvejar/ms1:latest
          name: ms1
          ports:
            - containerPort: 0
              protocol: TCP
      restartPolicy: Always
