apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\Program Files\Kompose\kompose.exe convert
    kompose.version: 1.36.0 (ae2a39403)
  labels:
    io.kompose.service: ms1
  name: ms1
spec:
  type: LoadBalancer
  ports:
    - name: "0"
      port: 0
      targetPort: 0
  selector:
    io.kompose.service: ms1
