apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Program Files\Kompose\kompose.exe convert
    kompose.version: 1.36.0 (ae2a39403)
  labels:
    io.kompose.service: ms2
  name: ms2
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: ms2
  template:
    metadata:
      annotations:
        kompose.cmd: C:\Program Files\Kompose\kompose.exe convert
        kompose.version: 1.36.0 (ae2a39403)
      labels:
        io.kompose.service: ms2
    spec:
      containers:
        - env:
            - name: EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE
              value: http://eureka-server:8761/eureka
            - name: PORT
              value: "8002"
            - name: SPRING_CLOUD_CONFIG_URI
              value: http://config-server:8081
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          image: matiasvejar/ms2:latest
          name: ms2
          ports:
            - containerPort: 8002
              protocol: TCP
      restartPolicy: Always
