apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Program Files\Kompose\kompose.exe convert
    kompose.version: 1.36.0 (ae2a39403)
  labels:
    io.kompose.service: ms3
  name: ms3
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: ms3
  template:
    metadata:
      annotations:
        kompose.cmd: C:\Program Files\Kompose\kompose.exe convert
        kompose.version: 1.36.0 (ae2a39403)
      labels:
        io.kompose.service: ms3
    spec:
      containers:
        - env:
            - name: EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE
              value: http://eureka-server:8761/eureka
            - name: PORT
              value: "8003"
            - name: SPRING_CLOUD_CONFIG_URI
              value: http://config-server:8081
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          image: matiasvejar/ms3:latest
          name: ms3
          ports:
            - containerPort: 8003
              protocol: TCP
      restartPolicy: Always
