apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms3
  labels:
    io.kompose.service: ms3
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: ms3
  template:
    metadata:
      labels:
        io.kompose.service: ms3
    spec:
      containers:
        - name: ms3
          image: matiasvejar/ms3:latest
          env:
            - name: EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE
              value: http://eureka-server:8761/eureka
            - name: PORT
              value: "0"
            - name: SPRING_CLOUD_CONFIG_URI
              value: http://config-server:8081
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
      restartPolicy: Always
