apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Program Files\Kompose\kompose.exe convert
    kompose.version: 1.36.0 (ae2a39403)
  labels:
    io.kompose.service: ms4
  name: ms4
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: ms4
  template:
    metadata:
      annotations:
        kompose.cmd: C:\Program Files\Kompose\kompose.exe convert
        kompose.version: 1.36.0 (ae2a39403)
      labels:
        io.kompose.service: ms4
    spec:
      containers:
        - env:
            - name: EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE
              value: http://eureka-server:8761/eureka
            - name: PORT
              value: "8004"
            - name: SPRING_CLOUD_CONFIG_URI
              value: http://config-server:8081
          image: matiasvejar/ms4:latest
          name: ms4
          ports:
            - containerPort: 8004
              protocol: TCP
      restartPolicy: Always
