apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\Program Files\Kompose\kompose.exe convert
    kompose.version: 1.36.0 (ae2a39403)
  labels:
    io.kompose.service: ms6
  name: ms6
spec:
  type: LoadBalancer
  ports:
    - name: "8006"
      port: 8006
      targetPort: 8006
  selector:
    io.kompose.service: ms6
