apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\Program Files\Kompose\kompose.exe convert
    kompose.version: 1.36.0 (ae2a39403)
  labels:
    io.kompose.service: ms7
  name: ms7
spec:
  type: LoadBalancer
  ports:
    - name: "8007"
      port: 8007
      targetPort: 8007
  selector:
    io.kompose.service: ms7
