spring:
  application:
    name: eureka-server
  config:
    import: optional:configserver:http://localhost:8888

server:
  port: 8761

eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      default-zone: http://localhost:8761/eureka/
