server:
  port: 8080
  max-http-header-size: 16384

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:5173"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
            allowedHeaders: "*"
            allowCredentials: true
      httpclient:
        connect-timeout: 5000
        response-timeout: 10s    
      routes:
        - id: ms1
          uri: lb://ms1
          predicates:
            - Path=/api/tarifas/**
        - id: ms2
          uri: lb://ms2
          predicates:
            - Path=/api/descuentoscantidad/**
        - id: ms3
          uri: lb://ms3
          predicates:
            - Path=/api/frecuencia/**
        - id: ms4
          uri: lb://ms4
          predicates:
            - Path=/api/fecha-descuento/**
        - id: ms5
          uri: lb://ms5
          predicates:
            - Path=/api/reservas
            - Path=/api/reservas/
            - Path=/api/reservas/**
            - Path=/api/users/**
          filters:
            - StripPrefix=1
        - id: ms6
          uri: lb://ms6
          predicates:
            - Path=/api/rack/**
        - id: ms7
          uri: lb://ms7
          predicates:
            - Path=/api/reportes/**