server:
  port: 8080
  max-http-header-size: 16384

management:
  endpoints:
    web:
      exposure:
        include: health,info

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
  instance:
    preferIpAddress: true    # Change to true
    hostname: ${spring.application.name}

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: ["*"]
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
            allowedHeaders: "*"
            allowCredentials: false
      routes:
        - id: ms1
          uri: lb://ms1
          predicates:
            - Path=/api/tarifas/**
        - id: ms2
          uri: lb://ms2
          predicates:
            - Path=/api/descuentoscantidad/**
        - id: ms3
          uri: lb://ms3
          predicates:
            - Path=/api/frecuencia/**
        - id: ms4
          uri: lb://ms4
          predicates:
            - Path=/api/fecha-descuento/**
        - id: ms5
          uri: lb://ms5
          predicates:
            - Path=/api/reservas/**,/api/users/**
        - id: ms6
          uri: lb://ms6
          predicates:
            - Path=/api/rack/**
        - id: ms7
          uri: lb://ms7
          predicates:
            - Path=/api/reportes/**